add support for types_check option
whisklabs/airflow-clickhouse-plugin pull request #37
Opened 2022-02-13 19:51 UTC by r3b-fish

2022-02-14 05:37 UTC, bryzgaloff requested changes
Good, thank you! Minor style changes required and I will merge and publish.

2022-02-14 05:37 UTC, bryzgaloff commented on tests/integration/test_hook.py
> +        )
```suggestion
        self._hook.run(f'DROP TABLE IF EXISTS {self._temp_table_name}')
```

2022-02-14 05:37 UTC, bryzgaloff commented on tests/integration/test_hook.py
> +        )
```suggestion
        result = self._hook.run(f'INSERT INTO {self._temp_table_name} (test_field) VALUES', [(3,)])
```

2022-02-14 06:40 UTC, r3b-fish commented
I've done cosmetic changes. Can you check it. Thanks for quick feedback!

2022-04-07 07:47 UTC, bryzgaloff approved these changes

2022-04-07 07:48 UTC, bryzgaloff commented
Tough time in Russia, have not had a chance to have a look. Thanks, deploying.

2022-04-07 07:49 UTC, merged

2022-04-07 08:05 UTC, bryzgaloff commented
Publishes as https://pypi.org/project/airflow-clickhouse-plugin/0.8.1/